run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - docs
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - gocritic
    - exportloopref
    - goconst
    - gocognit
    - gocyclo
    - goerr113
    - gofumpt
    - gomnd
    - goprintffuncname
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
      - name: comment-spacings
        severity: warning
      - name: range
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range-val-in-closure
        severity: warning
      - name: defer
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-naming
        severity: warning
      - name: range
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: unexported-return
        severity: warning
      - name: time-naming
        severity: warning
      - name: context-keys-type
        severity: warning
      - name: context-as-argument
        severity: warning

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 15

  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

